server:
  port: 8080

spring:
  application:
    name: "api-gateway"

app:
  gateway:
    service-host: "http://localhost"
    path-prefix: "/api"
    routes:
      - id: "user"
        port: 8070
        paths:
          - "@/users"
          - "@/users/{segment}"
          - "@/login"
          - "/login"
      - id: "underwriter"
        port: 8071
        paths:
          - "@/applicants"
          - "@/applications"
          - "@/applicants/{segment}"
          - "@/applications/{segment}"
      - id: "account"
        port: 8072
        paths:
          - "@/accounts"
          - "@/accounts/{segment}"
          - "@/members/{segment}/accounts"
      - id: "bank"
        port: 8083
        paths:
          - "@/members"
          - "@/members/{segment}"
          - "@/branches"
          - "@/banks"
          - "@/banks/routing"
          - "@/banks/routing/{segment}"
          - "@/banks/id"
          - "@/banks/id/{segment}"
      - id: "transaction"
        port: 8073
        paths:
          - "@/transactions"
          - "@/transactions/{segment}"
          - "@/members/{segment}/transactions"
          - "@/accounts/{segment}/transactions"
    portal-origins:
      - "http://localhost:4200"
      - "http://localhost:3007"
      - "http://localhost:3000"
